In [66]:
import os
import numpy as np
import pandas as pd

import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
%matplotlib inline

#### 데이터 읽어오기

- pd.ExcelFile()
    - `Excel 파일의 메타데이터(시트이름) 확인 및 파일 내에 여러 시트에 접근`하기 위해 사용
    - 파일을 한번만 읽고 여러 시트를 반복적으로 사용할 때 유용함
    - 메타데이터를 확인하거나 여러 시트를 한번에 읽어와야 할 때 유용함
    - 파일을 한번 로드한 후 각 시트를 별도로 읽어와야 하므로, 특정 시트를 바로 읽어오는 데에 추가 단계가 필요함
 
- pd.read_excel()
    - Excel파일의 특정 시트 또는 여러 시트를 한번에 읽어오기 위해 사용
    - 특정 시트 또는 여러 시트를 바로 읽어올 수 있어 코드가 간결함
    - `시트 하나만 필요할때` 유용
    - 파일을 여러번 읽어야 할 때 비효율적일 수 있음

In [62]:
%%time

TMS = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx")
TMS_jungnang = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx", sheet_name='중랑구')
TMS_seongdong = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx", sheet_name='성동구')
TMS_mapo = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx", sheet_name='마포구')
TMS_gwangjin = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx", sheet_name='광진구')
TMS_gangdong = pd.read_excel("../../dataFiles/csv/airMeasurement/TMS_all.xlsx", sheet_name='강동구')

CPU times: total: 46 s
Wall time: 47.5 s


In [63]:
# 강동구 데이터셋 읽어오기 : 전체 및 각 sheet이름 확인
gangdong = pd.ExcelFile("../../dataFiles/csv/airMeasurement/강동구.xlsx")

sheet_names_GA = gangdong.sheet_names
print(sheet_names_GA)

['132', '136', '502', '503', '531', '572', '573', '625', '711', '789', '792']


In [70]:
%%time

gangdong_132 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='132')
gangdong_136 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='136')
gangdong_502 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='502')
gangdong_503 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='503')
gangdong_531 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='531')
gangdong_572 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='572')
gangdong_573 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='573')
gangdong_625 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='625')
gangdong_711 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='711')
gangdong_789 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='789')
gangdong_792 = pd.read_excel("../../dataFiles/csv/airMeasurement/강동구.xlsx", sheet_name='792')

CPU times: total: 1min 31s
Wall time: 1min 33s


In [71]:
# 광진구 데이터셋 읽어오기 : 전체 및 각 sheet이름 확인
gwangjin = pd.ExcelFile("../../dataFiles/csv/airMeasurement/광진구.xlsx")

sheet_names_GW = gwangjin.sheet_names
print(sheet_names_GW)

['112', '113', '508', '536', '537', '566', '582', '583', '629', '716', '744', '749', '794']


In [72]:
%%time

for sheet in sheet_names_GW:
    globals()[f'gwangjin_{sheet}'] = pd.read_excel("../../dataFiles/csv/airMeasurement/광진구.xlsx", sheet_name=sheet)

CPU times: total: 2min 3s
Wall time: 2min 7s


In [73]:
# 마포구 데이터셋 읽어오기 : 전체 및 각 sheet이름 확인
mapo = pd.ExcelFile("../../dataFiles/csv/airMeasurement/마포구.xlsx")

sheet_names_M = mapo.sheet_names
print(sheet_names_M)

['135', '137', '515', '516', '599', '600', '637', '706', '707', '714', '750', '781', '786']


In [74]:
# 마포구 데이터셋 시트분리
%%time

mapo_135 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='135')
mapo_137 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='137')
mapo_515 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='515')
mapo_516 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='516')
mapo_599 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='599')
mapo_600 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='600')
mapo_637 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='637')
mapo_706 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='706')
mapo_707 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='707')
mapo_714 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='714')
mapo_750 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='750')
mapo_781 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='781')
mapo_786 = pd.read_excel("../../dataFiles/csv/airMeasurement/마포구.xlsx", sheet_name='786')

CPU times: total: 2min 2s
Wall time: 2min 5s


In [56]:
# 성동구 데이터셋 읽어오기 : 전체 및 각 sheet이름 확인
seongdong = pd.ExcelFile("../../dataFiles/csv/airMeasurement/성동구.xlsx")

sheet_names_S = seongdong.sheet_names
print(sheet_names_S)

['114', '134', '141', '517', '552', '553', '607', '608', '639', '640', '718', '727', '740', '757', '761', '764', '772', '773']


In [75]:
%%time

for sheet in sheet_names_S:
    globals()[f'seongdong_{sheet}'] = pd.read_excel("../../dataFiles/csv/airMeasurement/성동구.xlsx", sheet_name=sheet)


CPU times: total: 2min 46s
Wall time: 2min 51s


In [76]:
# 중랑구 데이터셋 읽어오기 : 전체 및 각 sheet이름 확인
jungnang = pd.ExcelFile("../../dataFiles/csv/airMeasurement/중랑구.xlsx")

sheet_names_J = jungnang.sheet_names
print(sheet_names_J)

['117', '127', '139', '163', '170', '525', '619', '620', '621', '647', '648', '649', '730', '736', '755', '756']


In [77]:
%%time

for sheet in sheet_names_J:
    globals()[f'jungnang_{sheet}'] = pd.read_excel("../../dataFiles/csv/airMeasurement/중랑구.xlsx", sheet_name=sheet)

CPU times: total: 1min 22s
Wall time: 1min 24s


#### 데이터 구조파악

In [15]:
print(gangdong.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19011 entries, 0 to 19010
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       19011 non-null  object 
 1   월       19008 non-null  float64
 2   일       19008 non-null  float64
 3   시       19008 non-null  float64
 4   분       19008 non-null  float64
 5   측정소     19008 non-null  object 
 6   PM2.5   19011 non-null  object 
 7   PM10    19011 non-null  object 
 8   CH01    19011 non-null  object 
 9   CH02    19011 non-null  object 
 10  CH03    19011 non-null  object 
 11  CH04    19011 non-null  object 
 12  CH05    19011 non-null  object 
 13  CH06    19011 non-null  object 
 14  CH07    19011 non-null  object 
 15  CH08    19011 non-null  object 
 16  CH09    19011 non-null  object 
 17  CH10    19011 non-null  object 
 18  CH11    19011 non-null  object 
 19  CH12    19011 non-null  object 
 20  CH13    19011 non-null  object 
 21  CH14    19011 non-null  object 
 22

In [16]:
print(gwangjin.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19011 entries, 0 to 19010
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       19011 non-null  object 
 1   월       19008 non-null  float64
 2   일       19008 non-null  float64
 3   시       19008 non-null  float64
 4   분       19008 non-null  float64
 5   측정소     19008 non-null  object 
 6   PM2.5   19011 non-null  object 
 7   PM10    19011 non-null  object 
 8   CH01    19011 non-null  object 
 9   CH02    19011 non-null  object 
 10  CH03    19011 non-null  object 
 11  CH04    19011 non-null  object 
 12  CH05    19011 non-null  object 
 13  CH06    19011 non-null  object 
 14  CH07    19011 non-null  object 
 15  CH08    19011 non-null  object 
 16  CH09    19011 non-null  object 
 17  CH10    19011 non-null  object 
 18  CH11    19011 non-null  object 
 19  CH12    19011 non-null  object 
 20  CH13    19011 non-null  object 
 21  CH14    19011 non-null  object 
 22

In [17]:
print(mapo.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19012 entries, 0 to 19011
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       19012 non-null  object 
 1   월       19009 non-null  float64
 2   일       19009 non-null  float64
 3   시       19009 non-null  float64
 4   분       19009 non-null  float64
 5   측정소     19009 non-null  object 
 6   PM2.5   19012 non-null  object 
 7   PM10    19012 non-null  object 
 8   CH01    19012 non-null  object 
 9   CH02    19012 non-null  object 
 10  CH03    19012 non-null  object 
 11  CH04    19012 non-null  object 
 12  CH05    19012 non-null  object 
 13  CH06    19012 non-null  object 
 14  CH07    19012 non-null  object 
 15  CH08    19012 non-null  object 
 16  CH09    19012 non-null  object 
 17  CH10    19012 non-null  object 
 18  CH11    19012 non-null  object 
 19  CH12    19012 non-null  object 
 20  CH13    19012 non-null  object 
 21  CH14    19012 non-null  object 
 22

In [18]:
print(seongdong.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19013 entries, 0 to 19012
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       19013 non-null  object 
 1   월       19010 non-null  float64
 2   일       19010 non-null  float64
 3   시       19010 non-null  float64
 4   분       19010 non-null  float64
 5   측정소     19010 non-null  object 
 6   PM2.5   19013 non-null  object 
 7   PM10    19013 non-null  object 
 8   CH01    19013 non-null  object 
 9   CH02    19013 non-null  object 
 10  CH03    19013 non-null  object 
 11  CH04    19013 non-null  object 
 12  CH05    19013 non-null  object 
 13  CH06    19013 non-null  object 
 14  CH07    19013 non-null  object 
 15  CH08    19013 non-null  object 
 16  CH09    19013 non-null  object 
 17  CH10    19013 non-null  object 
 18  CH11    19013 non-null  object 
 19  CH12    19013 non-null  object 
 20  CH13    19013 non-null  object 
 21  CH14    19013 non-null  object 
 22

In [19]:
print(jungnang.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19011 entries, 0 to 19010
Data columns (total 17 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       19011 non-null  object 
 1   월       19008 non-null  float64
 2   일       19008 non-null  float64
 3   시       19008 non-null  float64
 4   분       19008 non-null  float64
 5   측정소     19008 non-null  object 
 6   PM2.5   19011 non-null  object 
 7   PM10    19011 non-null  object 
 8   CH01    19011 non-null  object 
 9   CH02    19011 non-null  object 
 10  CH03    19011 non-null  object 
 11  CH04    19011 non-null  object 
 12  CH05    19011 non-null  object 
 13  CH06    19011 non-null  object 
 14  CH07    19011 non-null  object 
 15  CH08    19011 non-null  object 
 16  CH09    19011 non-null  object 
dtypes: float64(4), object(13)
memory usage: 2.5+ MB
None


In [14]:
print(TMS.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78613 entries, 0 to 78612
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78613 non-null  int64  
 1   월       78613 non-null  int64  
 2   일       78613 non-null  int64  
 3   시       78613 non-null  int64  
 4   분       78613 non-null  int64  
 5   측정소     78613 non-null  object 
 6   PM2.5   78613 non-null  object 
 7   PM10    78613 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   0 non-null      float64
 10  NO      78613 non-null  object 
 11  NO2     78613 non-null  object 
 12  NOx     78613 non-null  object 
 13  CO      78613 non-null  object 
 14  O3      78613 non-null  object 
 15  SO2     78613 non-null  object 
 16  WD      78613 non-null  object 
 17  WS      78613 non-null  object 
 18  TEMP    78613 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78613 non-null  object 
 21  UVB     0 non-null      float64
 22

In [26]:
print(TMS_jungnang.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78613 entries, 0 to 78612
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78613 non-null  int64  
 1   월       78613 non-null  int64  
 2   일       78613 non-null  int64  
 3   시       78613 non-null  int64  
 4   분       78613 non-null  int64  
 5   측정소     78613 non-null  object 
 6   PM2.5   78613 non-null  object 
 7   PM10    78613 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   0 non-null      float64
 10  NO      78613 non-null  object 
 11  NO2     78613 non-null  object 
 12  NOx     78613 non-null  object 
 13  CO      78613 non-null  object 
 14  O3      78613 non-null  object 
 15  SO2     78613 non-null  object 
 16  WD      78613 non-null  object 
 17  WS      78613 non-null  object 
 18  TEMP    78613 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78613 non-null  object 
 21  UVB     0 non-null      float64
 22

In [27]:
print(TMS_seongdong.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78584 entries, 0 to 78583
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78584 non-null  int64  
 1   월       78584 non-null  int64  
 2   일       78584 non-null  int64  
 3   시       78584 non-null  int64  
 4   분       78584 non-null  int64  
 5   측정소     78584 non-null  object 
 6   PM2.5   78584 non-null  object 
 7   PM10    78584 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   0 non-null      float64
 10  NO      78584 non-null  object 
 11  NO2     78584 non-null  object 
 12  NOx     78584 non-null  object 
 13  CO      78584 non-null  object 
 14  O3      78584 non-null  object 
 15  SO2     78584 non-null  object 
 16  WD      78584 non-null  object 
 17  WS      78584 non-null  object 
 18  TEMP    78584 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78584 non-null  object 
 21  UVB     0 non-null      float64
 22

In [28]:
print(TMS_mapo.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78613 entries, 0 to 78612
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78613 non-null  int64  
 1   월       78613 non-null  int64  
 2   일       78613 non-null  int64  
 3   시       78613 non-null  int64  
 4   분       78613 non-null  int64  
 5   측정소     78613 non-null  object 
 6   PM2.5   78613 non-null  object 
 7   PM10    78613 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   0 non-null      float64
 10  NO      78613 non-null  object 
 11  NO2     78613 non-null  object 
 12  NOx     78613 non-null  object 
 13  CO      78613 non-null  object 
 14  O3      78613 non-null  object 
 15  SO2     78613 non-null  object 
 16  WD      78613 non-null  object 
 17  WS      78613 non-null  object 
 18  TEMP    78613 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78613 non-null  object 
 21  UVB     0 non-null      float64
 22

In [29]:
print(TMS_gwangjin.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78614 entries, 0 to 78613
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78614 non-null  int64  
 1   월       78614 non-null  int64  
 2   일       78614 non-null  int64  
 3   시       78614 non-null  int64  
 4   분       78614 non-null  int64  
 5   측정소     78614 non-null  object 
 6   PM2.5   78614 non-null  object 
 7   PM10    78614 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   78614 non-null  object 
 10  NO      78614 non-null  object 
 11  NO2     78614 non-null  object 
 12  NOx     78614 non-null  object 
 13  CO      78614 non-null  object 
 14  O3      78614 non-null  object 
 15  SO2     78614 non-null  object 
 16  WD      78614 non-null  object 
 17  WS      78614 non-null  object 
 18  TEMP    78614 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78614 non-null  object 
 21  UVB     0 non-null      float64
 22

In [30]:
print(TMS_gangdong.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78615 entries, 0 to 78614
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   년       78615 non-null  int64  
 1   월       78615 non-null  int64  
 2   일       78615 non-null  int64  
 3   시       78615 non-null  int64  
 4   분       78615 non-null  int64  
 5   측정소     78615 non-null  object 
 6   PM2.5   78615 non-null  object 
 7   PM10    78615 non-null  object 
 8   TSP     0 non-null      float64
 9   PM1.0   0 non-null      float64
 10  NO      78615 non-null  object 
 11  NO2     78615 non-null  object 
 12  NOx     78615 non-null  object 
 13  CO      78615 non-null  object 
 14  O3      78615 non-null  object 
 15  SO2     78615 non-null  object 
 16  WD      78615 non-null  object 
 17  WS      78615 non-null  object 
 18  TEMP    78615 non-null  object 
 19  UVA     0 non-null      float64
 20  HUM     78615 non-null  object 
 21  UVB     0 non-null      float64
 22

#### 데이터 요소파악

In [78]:
print(TMS['월'].unique())
print(TMS_jungnang['월'].unique())
print(TMS_seongdong['월'].unique())
print(TMS_mapo['월'].unique())
print(TMS_gwangjin['월'].unique())
print(TMS_gangdong['월'].unique())

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [82]:
# 랩코_강동구 '월' 열 확인
for sheet in sheet_names_GA:
    df = gangdong.parse(sheet)
    print(f"{sheet} sheet '월' :", df['월'].unique())

132 sheet '월' : [ 7.  8.  9. nan]
136 sheet '월' : [ 7.  8.  9. nan]
502 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
503 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
531 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
572 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
573 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
625 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
711 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
789 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
792 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]


In [83]:
# 랩코_광진구 '월' 열 확인
for sheet in sheet_names_GW:
    df = gwangjin.parse(sheet)
    print(f"{sheet} sheet '월' :", df['월'].unique())

112 sheet '월' : [ 7.  8.  9. nan]
113 sheet '월' : [ 7.  8.  9. nan]
508 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
536 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
537 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
566 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
582 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
583 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
629 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
716 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
744 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
749 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
794 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]


In [ ]:
# 랩코_마포구 '월' 열 확인
for sheet in sheet_names_M:
    df = mapo.parse(sheet)
    print(f"{sheet} sheet '월' :", df['월'].unique())

135 sheet '월' : [ 7.  8.  9. nan]
137 sheet '월' : [ 7.  8.  9. nan]
515 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
516 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
599 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
600 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
637 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
706 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]
707 sheet '월' : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. nan]


In [ ]:
# 랩코_성동구 '월' 열 확인
for sheet in sheet_names_S:
    df = seongdong.parse(sheet)
    print(f"{sheet} sheet '월' :", df['월'].unique())

In [ ]:
# 랩코_중랑구 '월' 열 확인
for sheet in sheet_names_J:
    df = jungnang.parse(sheet)
    print(f"{sheet} sheet '월' :", df['월'].unique())